name: esalonbusiness
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: 
  firebase_core: 0.4.4
  firebase_auth: 0.15.3
  firebase_analytics: 
  rxdart: ^0.20.0
  google_sign_in: 
  transparent_image: 
  shared_preferences: ^0.5.6+3
  firebase_storage: 
  image_picker: 
  random_string: 
  # firebase_messaging: ^5.1.6
  # web_socket_channel: ^1.0.13
  fluttertoast: ^3.1.3
  google_maps_flutter: 
  location: 
  cached_network_image: 
  flutter_local_notifications: 
  image_cropper: 
  photo_view: 
  url_launcher: 
  eva_icons_flutter: 
  cloud_firestore: 
  video_player: 
  country_code_picker: 
  onesignal_flutter: ^2.3.4
  cloud_functions:  
  flutter_ringtone_player: 
  apple_sign_in: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
#   flutter_native_splash: ^0.1.9
  flutter_launcher_icons: ^0.7.0

# flutter_native_splash:
#   image: assets/splash.png
#   color: "ffffff"
  
flutter_icons:
  android: true
  ios: false
  image_path_android: "assets/ic_launcher.png"
  image_path: "assets/ic_launcher.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/whatsapp.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
       - family: NunitoSans
         fonts:
           - asset: fonts/NunitoSans-Regular.ttf
             weight: 600
           - asset: fonts/NunitoSans-ExtraLight.ttf
             weight: 100
           - asset: fonts/NunitoSans-Light.ttf
             weight: 200
           - asset: fonts/NunitoSans-SemiBold.ttf
             weight: 700
           - asset: fonts/NunitoSans-Bold.ttf
             weight: 800
           - asset: fonts/NunitoSans-ExtraBold.ttf
             weight: 900
       - family: OverpassMono
         fonts:
           - asset: fonts/OverpassMono-Regular.ttf
             weight: 600
           - asset: fonts/OverpassMono-Light.ttf
             weight: 100
       - family: Comfortaa
         fonts:
           - asset: fonts/Comfortaa-Bold.ttf
             weight: 700
           - asset: fonts/Comfortaa-Regular.ttf
             weight: 400
           - asset: fonts/Comfortaa-Light.ttf
             weight: 300
       - family: Caveat
         fonts:
           - asset: fonts/Caveat-Bold.ttf
       - family: Meriada
         fonts:
           - asset: fonts/MeriendaOne-Regular.ttf
       - family: Monoton
         fonts:
           - asset: fonts/Monoton-Regular.ttf
